//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class allergy
    {
        public int FKpt_id { get; set; }
        public int FKclass_id { get; set; }
        public string notes { get; set; }
    
        public virtual classifi classifi { get; set; }
        public virtual patient patient { get; set; }
    }
}
