//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic_details
    {
        public string clinic_name { get; set; }
        public string clinic_address { get; set; }
        public string field { get; set; }
        public string phone { get; set; }
        public string monile { get; set; }
        public string mail { get; set; }
        public byte[] clinicLogo { get; set; }
        public string notes { get; set; }
    }
}
