//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class drug
    {
        public int drug_id { get; set; }
        public int FKclass_id { get; set; }
        public string drug_name { get; set; }
        public string form { get; set; }
        public string default_quantity { get; set; }
        public string unit { get; set; }
        public string active { get; set; }
    
        public virtual classifi classifi { get; set; }
    }
}
