//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class examination
    {
        public int FKvist_id { get; set; }
        public Nullable<int> pulse { get; set; }
        public string bp { get; set; }
        public Nullable<decimal> temp { get; set; }
        public Nullable<decimal> o2 { get; set; }
        public Nullable<decimal> rr { get; set; }
        public Nullable<decimal> rbs { get; set; }
        public Nullable<decimal> bmi { get; set; }
        public string hand { get; set; }
        public string arm { get; set; }
        public string neck { get; set; }
        public string face { get; set; }
        public string lower_limb { get; set; }
        public string cardiacEx { get; set; }
        public string chestEx { get; set; }
        public string abdominalEx { get; set; }
        public byte[] ecg { get; set; }
        public string ecg_notes { get; set; }
    
        public virtual vist vist { get; set; }
    }
}
