//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoo
    {
        public int FKvist_id { get; set; }
        public string SysName { get; set; }
        public string SympName { get; set; }
    
        public virtual vist vist { get; set; }
    }
}
