//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class management_plan
    {
        public int FKvisit_id { get; set; }
        public Nullable<int> FKdrug_id { get; set; }
        public string prc_english { get; set; }
        public string prc_arabic { get; set; }
    
        public virtual vist vist { get; set; }
    }
}
