//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class past_med_history
    {
        public int FKvisit_id { get; set; }
        public string chronic_diseas { get; set; }
        public string surgical_interv { get; set; }
        public string hospital_admi { get; set; }
        public string drug_hist { get; set; }
        public string notes { get; set; }
    
        public virtual vist vist { get; set; }
    }
}
