//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_lab
    {
        public int FKvisit_id { get; set; }
        public int FKtest_id { get; set; }
        public Nullable<decimal> resault { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
    
        public virtual lab_tests lab_tests { get; set; }
        public virtual vist vist { get; set; }
    }
}
