//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class sign
    {
        public int sign_id { get; set; }
        public int sys_id { get; set; }
        public string sign_name { get; set; }
    
        public virtual syst syst { get; set; }
    }
}
