//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sliding_menue
{
    using System;
    using System.Collections.Generic;
    
    public partial class social_history
    {
        public int FKvisit_id { get; set; }
        public string smoking_status { get; set; }
        public string alcohol_status { get; set; }
        public string drugs { get; set; }
        public string driving { get; set; }
        public string notesSocial { get; set; }
    
        public virtual vist vist { get; set; }
    }
}
